# -*- coding: utf-8 -*-
"""ProjetoAnaliseGames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUvkPHo8mD03TVftsWMJ3SP9rzkVggjA

Bootcamp Santander Code Girls — DIO  

Este projeto reimagina o processo de ETL apresentado no desafio da DIO, aplicando o mesmo conceito ao domínio de vendas de jogos eletrônicos.  

 O objetivo deste notebook é demonstrar:  
- Extração de dados (E)  
- Transformação (T)  
- Carregamento (L)  
- Exploração e visualização dos insights  

Os dados foram analisados para entender o comportamento de vendas globais por gênero, plataforma e identificar os jogos de maior sucesso.
"""

import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

df = pd.DataFrame({
    "name": [
        "Super Mario Bros", "Mario Kart Wii", "Wii Sports",
        "Pokemon Red/Blue", "Tetris", "GTA V",
        "PUBG", "FIFA 21", "The Last of Us", "Minecraft"
    ],
    "genre": [
        "Plataforma", "Corrida", "Esportes",
        "RPG", "Puzzle", "Ação",
        "Battle Royale", "Esportes", "Ação", "Sandbox"
    ],
    "year": [1985, 2008, 2006, 1996, 1989, 2013, 2017, 2020, 2013, 2011],
    "global_sales": [40.2, 37.3, 82.8, 31.3, 43.0, 29.0, 70.0, 12.3, 20.0, 238.0]
})


df.columns = df.columns.str.lower()

if 'genre' not in df.columns or 'global_sales' not in df.columns:
    raise RuntimeError(
        "Colunas 'genre' ou 'global_sales' não encontradas. Colunas disponíveis: "
        + ", ".join(df.columns)
    )

sales_by_genre = df.groupby("genre")["global_sales"].sum().sort_values()

plt.figure(figsize=(10, 6))
sales_by_genre.plot(kind="barh")
plt.title("Vendas Globais por Gênero")
plt.xlabel("Milhões")
plt.ylabel("Gênero")
plt.tight_layout()
plt.show()

print("Top 10 jogos por vendas globais:")

top10 = df.nlargest(10, "global_sales")
display(top10[['name', 'year', 'global_sales']])

















